### ISSUE TITLE
M1 macで実行できない

### ISSUE THREAD

**Issue by Hayao0819** [FascodeNet/flast-chromium#14]
Alpha28です

<img width="260" alt="image" src="https://user-images.githubusercontent.com/32128205/184332369-d5374db4-bc17-407b-bc17-8fa90f0ce2b5.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/32128205/184333289-b9e1e007-d2a3-4ad0-9297-d0d115251f54.png">

**Comment by Aoichaan0513** [comment]
恐らくユニバーサルビルドを実行すると正常に動作するかと思います。
https://github.com/FascodeNet/flast-chromium/releases/tag/v1.0.0-alpha.29
