### ISSUE TITLE
新しいタブの画質について

### ISSUE THREAD

**Issue by surapunoyousei** [FascodeNet/flast-chromium#15]
新しいタブが現在ランダムに設定されており、大きさが指定されていないような気がするので、

「 https://source.unsplash.com/random/1920x1280 」などに設定してもいいと思います。

**Comment by surapunoyousei** [comment]
https://github.com/FascodeNet/flast-chromium/blob/cc7a9bf71bc978e47bd127737b5ea35700919d60/src/renderer/views/pages/home/components/PageContent/styles.tsx#L14

変更を入れるならここでしょう。

**Comment by Aoichaan0513** [comment]
確認しました、ありがとうございます！
