### ISSUE TITLE
「ダーク」テーマを使用した際に「設定」タブの文字が読めなくなる

### ISSUE THREAD

**Issue by lunae-f** [FascodeNet/flast-chromium#2]
# 環境
- Windows 10 21H1
- [1.0.0-alpha.19](https://github.com/FascodeNet/flast-chromium/releases/tag/v1.0.0-alpha.19)
[Flast-Web-Setup-1.0.0-alpha.19.exe](https://github.com/FascodeNet/flast-chromium/releases/download/v1.0.0-alpha.19/Flast-Web-Setup-1.0.0-alpha.19.exe)
# 不具合内容
「ダーク」テーマを使用すると背景が濃いグレーになりますが、フォントが黒になっているため、大変読みづらいです。
# 画像
![image](https://user-images.githubusercontent.com/62279412/153162973-4b68fbda-7c76-466b-9f2d-b02c4d6a3011.png)

**Comment by Aoichaan0513** [comment]
ガチバグなので頑張ります

**Comment by Aoichaan0513** [comment]
修正しました。
