### ISSUE TITLE
Windows で最新ビルド（Alpha 34）が起動しない

### ISSUE THREAD

**Issue by Ryosuke-Asano** [FascodeNet/flast-chromium#23]
いそがしいだろうし、だいぶ前にインストールして報告するか迷ったけど一応。

![image](https://user-images.githubusercontent.com/73892113/234804676-c31a96cd-5488-4a33-af9f-e4af154c7dc3.png)

**Comment by Aoichaan0513** [comment]
今月までに修正します。ありがとうございます！

**Comment by surapunoyousei** [comment]
死なない程度に頑張って下さい！()

**Comment by Aoichaan0513** [comment]
取り急ぎ修正しました。[macOS 以外の環境で起動しない問題を修正](https://github.com/FascodeNet/flast-chromium/commit/e389f40efd09ba55a864664b8035ed4339da0d03)

**Comment by Ryosuke-Asano** [comment]
お疲れ様！

2023年4月29日(土) 0:28 Aoichaan0513 ***@***.***>:

**Comment by Aoichaan0513** [comment]
自動ビルドが完了してたので、もしよければお手隙の際に問題が解決しているか検証していただけると嬉しいです！

Windows 版をダウンロードして展開後、`nsis-web` フォルダ内の `Flast Web Setup 1.0.0-alpha.34.exe` を実行
https://github.com/FascodeNet/flast-chromium/actions/runs/4832237644

**Comment by Ryosuke-Asano** [comment]
起動確認しました！
