### ISSUE TITLE
URLのバーをクリックしてから入力可能になるまで時間がかかる

### ISSUE THREAD

**Issue by lunae-f** [FascodeNet/flast-chromium#4]
## 環境
- Windows 10 21H1
- [Flast-Web-Setup-1.0.0-alpha.19.exe](https://github.com/FascodeNet/flast-chromium/releases/download/v1.0.0-alpha.19/Flast-Web-Setup-1.0.0-alpha.19.exe)
## 内容
タイトルの通りです。クリックしてから入力可能状態のなるまでワンテンポ遅れます。

**Comment by lunae-f** [comment]
訂正
Windowsのバージョンは21H2でした。念の為お伝えしておきます。すみません。

**Comment by Aoichaan0513** [comment]
サジェストを出す為にアドレスバーの長さを変えてから表示させるのでどうしてもワンテンポ遅延が発生します。
仕様と考えてもらえれば助かります
